
// This file was auto-generated by ML.NET Model Builder. 

using CRASML_ConsoleApp;

// Create single instance of sample data from first line of dataset for model input
CRASML.ModelInput sampleData = new CRASML.ModelInput()
{
    LoanAmount = 1068.72F,
    AnnualIncome = 34847.84F,
    MonthlyNetSalary = 3037.99F,
    InterestRate = 6F,
    NumberOfLoan = 1F,
    NumberOfDelayedPayment = 1F,
    OutstandingDebt = 605.03F,
    DebtToIncomeRatio = 20.83F,
    MonthsOfCreditHistory = 323F,
    PaymentOfMinimumAmount = 0F,
    MonthlyInstallmentAmount = 18.82F,
    AmountInvestedMonthly = 130.12F,
    MonthlyBalance = 444.87F,
};

// Make a single prediction on the sample data and print results
var predictionResult = CRASML.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual CreditScore with predicted CreditScore from sample data...\n\n");


Console.WriteLine($"LoanAmount: {1068.72F}");
Console.WriteLine($"AnnualIncome: {34847.84F}");
Console.WriteLine($"MonthlyNetSalary: {3037.99F}");
Console.WriteLine($"InterestRate: {6F}");
Console.WriteLine($"NumberOfLoan: {1F}");
Console.WriteLine($"NumberOfDelayedPayment: {1F}");
Console.WriteLine($"OutstandingDebt: {605.03F}");
Console.WriteLine($"DebtToIncomeRatio: {20.83F}");
Console.WriteLine($"MonthsOfCreditHistory: {323F}");
Console.WriteLine($"PaymentOfMinimumAmount: {0F}");
Console.WriteLine($"MonthlyInstallmentAmount: {18.82F}");
Console.WriteLine($"AmountInvestedMonthly: {130.12F}");
Console.WriteLine($"MonthlyBalance: {444.87F}");
Console.WriteLine($"CreditScore: {596F}");


Console.WriteLine($"\n\nPredicted CreditScore: {predictionResult.Score}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

