// <auto-generated />
using System;
using CreditRiskAssessment.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CreditRiskAssessment.Migrations
{
    [DbContext(typeof(CRASDbContext))]
    partial class CRASDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CreditRiskAssessment.Entities.AssessedCustomer", b =>
                {
                    b.Property<string>("BVN")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<decimal>("AmountInvestedMonthly")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AnnualIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("AssessedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("CreditRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DebtToIncomeRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyInstallmentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyNetSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MonthsOfCreditHistory")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfDelayedPayment")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfLoan")
                        .HasColumnType("int");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OutstandingDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PaymentOfMinimumAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PredictedCreditScore")
                        .HasColumnType("int");

                    b.HasKey("BVN");

                    b.ToTable("AssessedCustomers");
                });

            modelBuilder.Entity("CreditRiskAssessment.Entities.Customer", b =>
                {
                    b.Property<int>("BVN")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BVN"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<decimal>("AmountInvestedMonthly")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AnnualIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyInstallmentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyNetSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MonthsOfCreditHistory")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfDelayedPayment")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfLoan")
                        .HasColumnType("int");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OutstandingDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PaymentOfMinimumAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BVN");

                    b.ToTable("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
