// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace CreditRiskAssessment_Test
{
    public partial class CRASML
    {
        /// <summary>
        /// model input class for CRASML.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"LoanAmount")]
            public float LoanAmount { get; set; }

            [ColumnName(@"AnnualIncome")]
            public float AnnualIncome { get; set; }

            [ColumnName(@"MonthlyNetSalary")]
            public float MonthlyNetSalary { get; set; }

            [ColumnName(@"InterestRate")]
            public float InterestRate { get; set; }

            [ColumnName(@"NumberOfLoan")]
            public float NumberOfLoan { get; set; }

            [ColumnName(@"NumberOfDelayedPayment")]
            public float NumberOfDelayedPayment { get; set; }

            [ColumnName(@"OutstandingDebt")]
            public float OutstandingDebt { get; set; }

            [ColumnName(@"DebtToIncomeRatio")]
            public float DebtToIncomeRatio { get; set; }

            [ColumnName(@"MonthsOfCreditHistory")]
            public float MonthsOfCreditHistory { get; set; }

            [ColumnName(@"PaymentOfMinimumAmount")]
            public float PaymentOfMinimumAmount { get; set; }

            [ColumnName(@"MonthlyInstallmentAmount")]
            public float MonthlyInstallmentAmount { get; set; }

            [ColumnName(@"AmountInvestedMonthly")]
            public float AmountInvestedMonthly { get; set; }

            [ColumnName(@"MonthlyBalance")]
            public float MonthlyBalance { get; set; }

            [ColumnName(@"CreditScore")]
            public float CreditScore { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for CRASML.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"LoanAmount")]
            public float LoanAmount { get; set; }

            [ColumnName(@"AnnualIncome")]
            public float AnnualIncome { get; set; }

            [ColumnName(@"MonthlyNetSalary")]
            public float MonthlyNetSalary { get; set; }

            [ColumnName(@"InterestRate")]
            public float InterestRate { get; set; }

            [ColumnName(@"NumberOfLoan")]
            public float NumberOfLoan { get; set; }

            [ColumnName(@"NumberOfDelayedPayment")]
            public float NumberOfDelayedPayment { get; set; }

            [ColumnName(@"OutstandingDebt")]
            public float OutstandingDebt { get; set; }

            [ColumnName(@"DebtToIncomeRatio")]
            public float DebtToIncomeRatio { get; set; }

            [ColumnName(@"MonthsOfCreditHistory")]
            public float MonthsOfCreditHistory { get; set; }

            [ColumnName(@"PaymentOfMinimumAmount")]
            public float PaymentOfMinimumAmount { get; set; }

            [ColumnName(@"MonthlyInstallmentAmount")]
            public float MonthlyInstallmentAmount { get; set; }

            [ColumnName(@"AmountInvestedMonthly")]
            public float AmountInvestedMonthly { get; set; }

            [ColumnName(@"MonthlyBalance")]
            public float MonthlyBalance { get; set; }

            [ColumnName(@"CreditScore")]
            public float CreditScore { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("CRASML.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
